import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
    console.log("🌱 เริ่มการเพิ่ม Mockup Data...");

    // ล้างข้อมูลตาราง Component เก่าออกให้หมดก่อน (ถ้ามี)
    await prisma.component.deleteMany({});
    console.log("🧹 ล้างข้อมูลเดิมเรียบร้อย");

    // ข้อมูลสินค้า (Auto-generated by syncSeedFile)
    const allComponents = [
    {
        "id": "cmmdptw5l0003k76d9d8e9m1x",
        "name": "NVIDIA GeForce RTX 3060 Ti",
        "type": "GPU",
        "brand": "Nvidia",
        "price": 11900,
        "image": "https://media-cdn.bnn.in.th/126284/Gigabyte-VGA-RTX-3060-Ti-GAMING-OC-8GB-GDDR6-256-bit-1-square_medium.jpg",
        "description": null,
        "socket": null,
        "ramType": null,
        "formFactor": null,
        "capacity": null,
        "cpuSingleScore": null,
        "cpuMultiScore": null,
        "gpuScore": 19800,
        "vramGb": 8,
        "ramSpeed": null,
        "readWriteSpeed": null
    },
    {
        "id": "cmmdptw5q0004k76d1tha1a99",
        "name": "AMD Radeon RX 7800 XT",
        "type": "GPU",
        "brand": "AMD",
        "price": 18500,
        "image": "https://img.jib.co.th/jib_img/img_product/62534_00_pimg_20240904094056.jpg",
        "description": null,
        "socket": null,
        "ramType": null,
        "formFactor": null,
        "capacity": null,
        "cpuSingleScore": null,
        "cpuMultiScore": null,
        "gpuScore": 27500,
        "vramGb": 16,
        "ramSpeed": null,
        "readWriteSpeed": null
    },
    {
        "id": "cmmdptw5t0005k76dj6mzypju",
        "name": "NVIDIA GeForce RTX 4070 Ti SUPER",
        "type": "GPU",
        "brand": "Nvidia",
        "price": 32900,
        "image": "https://media-cdn.bnn.in.th/406456/Asus-VGA-TUF-RTX4070TIS-O16G-GAMING-16GB-GDDR6X-256-bit-1-square_medium.jpg",
        "description": null,
        "socket": null,
        "ramType": null,
        "formFactor": null,
        "capacity": null,
        "cpuSingleScore": null,
        "cpuMultiScore": null,
        "gpuScore": 31500,
        "vramGb": 16,
        "ramSpeed": null,
        "readWriteSpeed": null
    },
    {
        "id": "cmmdptw610007k76d3tqm7mtc",
        "name": "Kingston FURY Beast 32GB (16GBx2)",
        "type": "RAM",
        "brand": "Kingston",
        "price": 4500,
        "image": "https://media.studio7thailand.com/71253/Kingston-Ram-PC-DDR5-32GB5200-2x16GB-C40-FURY-Beast-Black-1-square_medium.jpg",
        "description": null,
        "socket": null,
        "ramType": "DDR5",
        "formFactor": null,
        "capacity": 32,
        "cpuSingleScore": null,
        "cpuMultiScore": null,
        "gpuScore": null,
        "vramGb": null,
        "ramSpeed": 5200,
        "readWriteSpeed": null
    },
    {
        "id": "cmmdptw6a0009k76dyfv20n5q",
        "name": "WD Blue SN580 500GB NVMe M.2",
        "type": "STORAGE",
        "brand": "Western Digital",
        "price": 1590,
        "image": "https://media-cdn.bnn.in.th/308117/WD-SSD-Blue-SN580-500GB-M.2-PCIe-NVMe-Gen-4-1-square_medium.jpg",
        "description": null,
        "socket": null,
        "ramType": null,
        "formFactor": null,
        "capacity": 500,
        "cpuSingleScore": null,
        "cpuMultiScore": null,
        "gpuScore": null,
        "vramGb": null,
        "ramSpeed": null,
        "readWriteSpeed": 4000
    },
    {
        "id": "cmn8q0pg60000mgn269qxxlf9",
        "name": "GEFORCE RTX 5060 TI",
        "type": "GPU",
        "brand": "GALAX",
        "price": 14900,
        "image": "https://www.jib.co.th/img_master/product/original/2025042809012476205_1.jpg",
        "description": "",
        "socket": null,
        "ramType": null,
        "formFactor": null,
        "capacity": null,
        "cpuSingleScore": null,
        "cpuMultiScore": null,
        "gpuScore": 22360,
        "vramGb": 8,
        "ramSpeed": null,
        "readWriteSpeed": null
    },
    {
        "id": "cmn8q3hsq0001mgn26kipt6dq",
        "name": "GEFORCE RTX 5060 TI",
        "type": "GPU",
        "brand": "GALAX",
        "price": 16900,
        "image": "https://galax.com/wp-content/uploads/2025/04/5060Ti_box-card_gx.png",
        "description": null,
        "socket": null,
        "ramType": null,
        "formFactor": null,
        "capacity": null,
        "cpuSingleScore": null,
        "cpuMultiScore": null,
        "gpuScore": 22674,
        "vramGb": 16,
        "ramSpeed": null,
        "readWriteSpeed": null
    },
    {
        "id": "cmmdptw520000k76dv37gr3wt",
        "name": "Intel Core i5-12400F",
        "type": "CPU",
        "brand": "Intel",
        "price": 4990,
        "image": "https://media.studio7thailand.com/74384/Intel-CPU-Core-i5-12400F-bx8071512400f-1-square_medium.jpg",
        "description": null,
        "socket": "LGA1700",
        "ramType": null,
        "formFactor": null,
        "capacity": null,
        "cpuSingleScore": 3500,
        "cpuMultiScore": 19500,
        "gpuScore": null,
        "vramGb": null,
        "ramSpeed": null,
        "readWriteSpeed": null
    },
    {
        "id": "cmmdptw5e0001k76da42ls31j",
        "name": "AMD Ryzen 5 7600X",
        "type": "CPU",
        "brand": "AMD",
        "price": 8500,
        "image": "https://media.studio7thailand.com/77607/AMD-CPU-Ryzen-5-7600X-100-100000593WOF-1-square_medium.jpg",
        "description": null,
        "socket": "AM5",
        "ramType": null,
        "formFactor": null,
        "capacity": null,
        "cpuSingleScore": 4200,
        "cpuMultiScore": 28500,
        "gpuScore": null,
        "vramGb": null,
        "ramSpeed": null,
        "readWriteSpeed": null
    },
    {
        "id": "cmmdptw5h0002k76d49eqqwks",
        "name": "Intel Core i7-14700K",
        "type": "CPU",
        "brand": "Intel",
        "price": 15900,
        "image": "https://media.studio7thailand.com/131711/Intel-CPU-Core-i7-14700k-bx8071514700k-1-square_medium.jpg",
        "description": null,
        "socket": "LGA1700",
        "ramType": null,
        "formFactor": null,
        "capacity": null,
        "cpuSingleScore": 4800,
        "cpuMultiScore": 54000,
        "gpuScore": null,
        "vramGb": null,
        "ramSpeed": null,
        "readWriteSpeed": null
    },
    {
        "id": "cmmdptw5x0006k76du1029ch1",
        "name": "Corsair Vengeance LPX 16GB (8GBx2)",
        "type": "RAM",
        "brand": "Corsair",
        "price": 1590,
        "image": "https://media.studio7thailand.com/83273/Corsair-Ram-PC-DDR4-16GB3200-2x8GB-CL16-Vengeance-LPX-Black-1-square_medium.jpg",
        "description": null,
        "socket": null,
        "ramType": "DDR4",
        "formFactor": null,
        "capacity": 16,
        "cpuSingleScore": null,
        "cpuMultiScore": null,
        "gpuScore": null,
        "vramGb": null,
        "ramSpeed": 3200,
        "readWriteSpeed": null
    },
    {
        "id": "cmmdptw660008k76d9k489ltz",
        "name": "Samsung 980 PRO 1TB NVMe M.2",
        "type": "STORAGE",
        "brand": "Samsung",
        "price": 3890,
        "image": "https://media-cdn.bnn.in.th/120286/Samsung-SSD-1TB-M.2-PCIe-NVMe-980-Pro-1-square_medium.jpg",
        "description": null,
        "socket": null,
        "ramType": null,
        "formFactor": null,
        "capacity": 1000,
        "cpuSingleScore": null,
        "cpuMultiScore": null,
        "gpuScore": null,
        "vramGb": null,
        "ramSpeed": null,
        "readWriteSpeed": 7000
    }
];

    console.log(`กำลังสร้างสินค้าทั้งหมด ${allComponents.length} ชิ้น...`);

    for (const component of allComponents) {
        await prisma.component.create({
            data: component
        });
    }

    console.log("✅ เพิ่มข้อมูลลง Database สำเร็จ!");
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
