import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
    console.log("🌱 เริ่มการเพิ่ม Mockup Data...");

    // ล้างข้อมูลตาราง Component เก่าออกให้หมดก่อน (ถ้ามี)
    await prisma.component.deleteMany({});
    console.log("🧹 ล้างข้อมูลเดิมเรียบร้อย");

    // ข้อมูลสินค้า (Auto-generated by syncSeedFile)
    const allComponents = [
    {
        "id": "cmmeka1ek000019so7rkc1rvx",
        "name": "Intel Core i5-12400F",
        "type": "CPU",
        "brand": "Intel",
        "price": 4990,
        "image": "https://media.studio7thailand.com/74384/Intel-CPU-Core-i5-12400F-bx8071512400f-1-square_medium.jpg",
        "description": null,
        "socket": "LGA1700",
        "ramType": "DDR4, DDR5",
        "formFactor": null,
        "capacity": null,
        "cpuSingleScore": 3500,
        "cpuMultiScore": 19500,
        "gpuScore": null,
        "vramGb": null,
        "ramSpeed": null,
        "readWriteSpeed": null
    },
    {
        "id": "cmmeka1et000119soinz8z2y4",
        "name": "AMD Ryzen 5 7600X",
        "type": "CPU",
        "brand": "AMD",
        "price": 8500,
        "image": "https://media.studio7thailand.com/77607/AMD-CPU-Ryzen-5-7600X-100-100000593WOF-1-square_medium.jpg",
        "description": null,
        "socket": "AM5",
        "ramType": "DDR5",
        "formFactor": null,
        "capacity": null,
        "cpuSingleScore": 4200,
        "cpuMultiScore": 28500,
        "gpuScore": null,
        "vramGb": null,
        "ramSpeed": null,
        "readWriteSpeed": null
    },
    {
        "id": "cmmeka1ev000219sok0q4opoy",
        "name": "Intel Core i7-14700K",
        "type": "CPU",
        "brand": "Intel",
        "price": 15900,
        "image": "https://media.studio7thailand.com/131711/Intel-CPU-Core-i7-14700k-bx8071514700k-1-square_medium.jpg",
        "description": null,
        "socket": "LGA1700",
        "ramType": "DDR4, DDR5",
        "formFactor": null,
        "capacity": null,
        "cpuSingleScore": 4800,
        "cpuMultiScore": 54000,
        "gpuScore": null,
        "vramGb": null,
        "ramSpeed": null,
        "readWriteSpeed": null
    },
    {
        "id": "cmmeka1ey000319so49sgw2ff",
        "name": "NVIDIA GeForce RTX 3060 Ti",
        "type": "GPU",
        "brand": "Nvidia",
        "price": 11900,
        "image": "https://media-cdn.bnn.in.th/126284/Gigabyte-VGA-RTX-3060-Ti-GAMING-OC-8GB-GDDR6-256-bit-1-square_medium.jpg",
        "description": null,
        "socket": null,
        "ramType": null,
        "formFactor": null,
        "capacity": null,
        "cpuSingleScore": null,
        "cpuMultiScore": null,
        "gpuScore": 19800,
        "vramGb": 8,
        "ramSpeed": null,
        "readWriteSpeed": null
    },
    {
        "id": "cmmeka1f0000419sozrjy9218",
        "name": "AMD Radeon RX 7800 XT",
        "type": "GPU",
        "brand": "AMD",
        "price": 18500,
        "image": "https://img.jib.co.th/jib_img/img_product/62534_00_pimg_20240904094056.jpg",
        "description": null,
        "socket": null,
        "ramType": null,
        "formFactor": null,
        "capacity": null,
        "cpuSingleScore": null,
        "cpuMultiScore": null,
        "gpuScore": 27500,
        "vramGb": 16,
        "ramSpeed": null,
        "readWriteSpeed": null
    },
    {
        "id": "cmmeka1f1000519soqp5258d5",
        "name": "NVIDIA GeForce RTX 4070 Ti SUPER",
        "type": "GPU",
        "brand": "Nvidia",
        "price": 32900,
        "image": "https://media-cdn.bnn.in.th/406456/Asus-VGA-TUF-RTX4070TIS-O16G-GAMING-16GB-GDDR6X-256-bit-1-square_medium.jpg",
        "description": null,
        "socket": null,
        "ramType": null,
        "formFactor": null,
        "capacity": null,
        "cpuSingleScore": null,
        "cpuMultiScore": null,
        "gpuScore": 31500,
        "vramGb": 16,
        "ramSpeed": null,
        "readWriteSpeed": null
    },
    {
        "id": "cmmeka1f3000619sodty2y7gu",
        "name": "Corsair Vengeance LPX 16GB (8GBx2)",
        "type": "RAM",
        "brand": "Corsair",
        "price": 1590,
        "image": "https://media.studio7thailand.com/83273/Corsair-Ram-PC-DDR4-16GB3200-2x8GB-CL16-Vengeance-LPX-Black-1-square_medium.jpg",
        "description": null,
        "socket": null,
        "ramType": "DDR4",
        "formFactor": null,
        "capacity": 16,
        "cpuSingleScore": null,
        "cpuMultiScore": null,
        "gpuScore": null,
        "vramGb": null,
        "ramSpeed": 3200,
        "readWriteSpeed": null
    },
    {
        "id": "cmmeka1f6000719soq3dnigl2",
        "name": "Kingston FURY Beast 32GB (16GBx2)",
        "type": "RAM",
        "brand": "Kingston",
        "price": 4500,
        "image": "https://media.studio7thailand.com/71253/Kingston-Ram-PC-DDR5-32GB5200-2x16GB-C40-FURY-Beast-Black-1-square_medium.jpg",
        "description": null,
        "socket": null,
        "ramType": "DDR5",
        "formFactor": null,
        "capacity": 32,
        "cpuSingleScore": null,
        "cpuMultiScore": null,
        "gpuScore": null,
        "vramGb": null,
        "ramSpeed": 5200,
        "readWriteSpeed": null
    },
    {
        "id": "cmmeka1f8000819so4w65exc3",
        "name": "Samsung 980 PRO 1TB NVMe M.2",
        "type": "STORAGE",
        "brand": "Samsung",
        "price": 3890,
        "image": "https://media-cdn.bnn.in.th/120286/Samsung-SSD-1TB-M.2-PCIe-NVMe-980-Pro-1-square_medium.jpg",
        "description": null,
        "socket": null,
        "ramType": null,
        "formFactor": null,
        "capacity": 1000,
        "cpuSingleScore": null,
        "cpuMultiScore": null,
        "gpuScore": null,
        "vramGb": null,
        "ramSpeed": null,
        "readWriteSpeed": 7000
    },
    {
        "id": "cmmeka1fb000919soxf9hghsc",
        "name": "WD Blue SN580 500GB NVMe M.2",
        "type": "STORAGE",
        "brand": "Western Digital",
        "price": 1590,
        "image": "https://media-cdn.bnn.in.th/308117/WD-SSD-Blue-SN580-500GB-M.2-PCIe-NVMe-Gen-4-1-square_medium.jpg",
        "description": null,
        "socket": null,
        "ramType": null,
        "formFactor": null,
        "capacity": 500,
        "cpuSingleScore": null,
        "cpuMultiScore": null,
        "gpuScore": null,
        "vramGb": null,
        "ramSpeed": null,
        "readWriteSpeed": 4000
    },
    {
        "id": "cmmsxct5c000013bnbfj0g3c8",
        "name": "test",
        "type": "CPU",
        "brand": "intel",
        "price": 5000,
        "image": null,
        "description": null,
        "socket": "zxc",
        "ramType": null,
        "formFactor": null,
        "capacity": null,
        "cpuSingleScore": 1234,
        "cpuMultiScore": 1234,
        "gpuScore": null,
        "vramGb": null,
        "ramSpeed": null,
        "readWriteSpeed": null
    },
    {
        "id": "cmmsxz6rb0000fg5bd7sjtzs8",
        "name": "test2",
        "type": "CPU",
        "brand": "intel",
        "price": 50000,
        "image": null,
        "description": "1\n2\n\n4\n5\n666666666",
        "socket": "asdasd",
        "ramType": null,
        "formFactor": null,
        "capacity": null,
        "cpuSingleScore": 111,
        "cpuMultiScore": 123123,
        "gpuScore": null,
        "vramGb": null,
        "ramSpeed": null,
        "readWriteSpeed": null
    },
    {
        "id": "cmng2uppx00003m6bq10ctxke",
        "name": "kkkkkkk",
        "type": "GPU",
        "brand": "ASUS",
        "price": 111111111,
        "image": "https://res.cloudinary.com/dgavtp1tj/image/upload/v1775049853/pc-builder-forum/nmfs4sqwnxporilfo7jz.png",
        "description": "asdasdasd",
        "socket": null,
        "ramType": null,
        "formFactor": null,
        "capacity": null,
        "cpuSingleScore": null,
        "cpuMultiScore": null,
        "gpuScore": 11111,
        "vramGb": 1111,
        "ramSpeed": null,
        "readWriteSpeed": null
    }
];

    console.log(`กำลังสร้างสินค้าทั้งหมด ${allComponents.length} ชิ้น...`);

    for (const component of allComponents) {
        await prisma.component.create({
            data: component
        });
    }

    console.log("✅ เพิ่มข้อมูลลง Database สำเร็จ!");
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
