import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
    console.log("🌱 เริ่มการเพิ่ม Mockup Data...");

    // ล้างข้อมูลตาราง Component เก่าออกให้หมดก่อน (ถ้ามี)
    await prisma.component.deleteMany({});
    console.log("🧹 ล้างข้อมูลเดิมเรียบร้อย");

    // ข้อมูลสินค้า (Auto-generated by syncSeedFile)
    const allComponents = [];

    console.log(`กำลังสร้างสินค้าทั้งหมด ${allComponents.length} ชิ้น...`);

    for (const component of allComponents) {
        await prisma.component.create({
            data: component
        });
    }

    console.log("✅ เพิ่มข้อมูลลง Database สำเร็จ!");
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
