import fs from "fs";
import path from "path";
import { PrismaClient } from "@prisma/client";

const globalForPrisma = globalThis as unknown as {
    prisma: PrismaClient | undefined;
};
const prisma = globalForPrisma.prisma ?? new PrismaClient();

export async function syncSeedFile() {
    // ปิดการทำงานบน Production (เพราะ Host จริงมักเป็น Read-only และข้อมูลอยู่บน DB หลักอยู่แล้ว)
    if (process.env.NODE_ENV === "production") {
        return;
    }

    try {
        const components = await prisma.component.findMany();

        // เอา createdAt, updatedAt ออกเพื่อให้ seed ใหม่ไม่รก
        const cleanComponents = components.map(c => {
            const { createdAt, updatedAt, ...rest } = c;
            return rest;
        });

        const fileContent = `import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
    console.log("🌱 เริ่มการเพิ่ม Mockup Data...");

    // ล้างข้อมูลตาราง Component เก่าออกให้หมดก่อน (ถ้ามี)
    await prisma.component.deleteMany({});
    console.log("🧹 ล้างข้อมูลเดิมเรียบร้อย");

    // ข้อมูลสินค้า (Auto-generated by syncSeedFile)
    const allComponents = ${JSON.stringify(cleanComponents, null, 4)};

    console.log(\`กำลังสร้างสินค้าทั้งหมด \${allComponents.length} ชิ้น...\`);

    for (const component of allComponents) {
        await prisma.component.create({
            data: component
        });
    }

    console.log("✅ เพิ่มข้อมูลลง Database สำเร็จ!");
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
`;

        const targetPath = path.join(process.cwd(), "prisma", "seed.ts");
        fs.writeFileSync(targetPath, fileContent, "utf-8");
        console.log("Auto-synced seed.ts successfully.");
    } catch (error) {
        console.error("Error auto-syncing seed.ts:", error);
    }
}
