import fs from "fs";
import path from "path";
import { PrismaClient } from "@prisma/client";

const globalForPrisma = globalThis as unknown as {
    prisma: PrismaClient | undefined;
};
const prisma = globalForPrisma.prisma ?? new PrismaClient();

export async function syncSeedFile() {
    // ปิดการทำงานบน Production (เพราะ Host จริงมักเป็น Read-only และข้อมูลอยู่บน DB หลักอยู่แล้ว)
    if (process.env.NODE_ENV === "production") {
        return;
    }

    try {
        // ใช้ `as any` เพื่อให้ได้ทุก field จาก DB จริงๆ
        // รวมถึง field ใหม่อย่าง `description` ที่อาจยังไม่อยู่ใน Prisma TypeScript type
        // (กรณีที่ยังไม่ได้ run `prisma generate` หลัง migrate)
        const components: any[] = await (prisma.component as any).findMany({
            orderBy: { createdAt: "asc" }
        });

        // เอา createdAt, updatedAt ออกเพื่อให้ seed ใหม่ไม่รก
        // และ reorder fields ให้ตรงกับ schema เสมอ
        const cleanComponents = components.map((c: any) => ({
            id:              c.id,
            name:            c.name,
            type:            c.type,
            brand:           c.brand,
            price:           c.price,
            image:           c.image ?? null,
            description:     c.description ?? null,
            socket:          c.socket ?? null,
            ramType:         c.ramType ?? null,
            formFactor:      c.formFactor ?? null,
            capacity:        c.capacity ?? null,
            tdp:             c.tdp ?? null,
            lengthMm:        c.lengthMm ?? null,
            maxGpuLength:    c.maxGpuLength ?? null,
            maxCoolerHeight: c.maxCoolerHeight ?? null,
            supportedMobo:   c.supportedMobo ?? null,
            psuFormFactor:   c.psuFormFactor ?? null,
            coolingType:     c.coolingType ?? null,
            cpuSingleScore:  c.cpuSingleScore ?? null,
            cpuMultiScore:   c.cpuMultiScore ?? null,
            gpuScore:        c.gpuScore ?? null,
            vramGb:          c.vramGb ?? null,
            ramSpeed:        c.ramSpeed ?? null,
            readSpeed:       c.readSpeed ?? null,
            writeSpeed:      c.writeSpeed ?? null,
            chipset:         c.chipset ?? null,
        }));

        const fileContent = `import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
    console.log("🌱 เริ่มการเพิ่ม Mockup Data...");

    // ล้างข้อมูลตาราง Component เก่าออกให้หมดก่อน (ถ้ามี)
    await prisma.component.deleteMany({});
    console.log("🧹 ล้างข้อมูลเดิมเรียบร้อย");

    // ข้อมูลสินค้า (Auto-generated by syncSeedFile)
    const allComponents = ${JSON.stringify(cleanComponents, null, 4)};

    console.log(\`กำลังสร้างสินค้าทั้งหมด \${allComponents.length} ชิ้น...\`);

    for (const component of allComponents) {
        await prisma.component.create({
            data: component
        });
    }

    console.log("✅ เพิ่มข้อมูลลง Database สำเร็จ!");
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
`;

        const targetPath = path.join(process.cwd(), "prisma", "seed.ts");
        fs.writeFileSync(targetPath, fileContent, "utf-8");
        console.log("Auto-synced seed.ts successfully.");
    } catch (error) {
        console.error("Error auto-syncing seed.ts:", error);
    }
}
